language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.12.9
  - 2.12.10
  - 2.13.0
  - 2.13.1
env:
  global:
    - CI=true
script:
  - sbt clean test
jdk:
  - oraclejdk11
before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx1024m"

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
