name: Codecov
on:
  push:
    branches: [master]
jobs:
  codecov:
    name: Run codecov on master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ivy-${{hashFiles('**/*.sbt')}}-${{matrix.scala}}
          restore-keys: ivy-
      - uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{hashFiles('**/*.sbt')}}-${{hashFiles('project/build.properties')}}-${{matrix.scala}}
          restore-keys: sbt-
      - name: Generate coverage report
        run: sbt clean coverage test coverageReport
      - uses: codecov/codecov-action@v1
